//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVDBQueueService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XIVDBQueueService.IQueueService")]
    public interface IQueueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/Enqueue", ReplyAction="http://tempuri.org/IQueueService/EnqueueResponse")]
        bool Enqueue(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/Enqueue", ReplyAction="http://tempuri.org/IQueueService/EnqueueResponse")]
        System.Threading.Tasks.Task<bool> EnqueueAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/Dequeue", ReplyAction="http://tempuri.org/IQueueService/DequeueResponse")]
        string Dequeue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/Dequeue", ReplyAction="http://tempuri.org/IQueueService/DequeueResponse")]
        System.Threading.Tasks.Task<string> DequeueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/ViewQueue", ReplyAction="http://tempuri.org/IQueueService/ViewQueueResponse")]
        string[] ViewQueue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/ViewQueue", ReplyAction="http://tempuri.org/IQueueService/ViewQueueResponse")]
        System.Threading.Tasks.Task<string[]> ViewQueueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueueServiceChannel : XIVDBQueueService.IQueueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueServiceClient : System.ServiceModel.ClientBase<XIVDBQueueService.IQueueService>, XIVDBQueueService.IQueueService {
        
        public QueueServiceClient() {
        }
        
        public QueueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Enqueue(string item) {
            return base.Channel.Enqueue(item);
        }
        
        public System.Threading.Tasks.Task<bool> EnqueueAsync(string item) {
            return base.Channel.EnqueueAsync(item);
        }
        
        public string Dequeue() {
            return base.Channel.Dequeue();
        }
        
        public System.Threading.Tasks.Task<string> DequeueAsync() {
            return base.Channel.DequeueAsync();
        }
        
        public string[] ViewQueue() {
            return base.Channel.ViewQueue();
        }
        
        public System.Threading.Tasks.Task<string[]> ViewQueueAsync() {
            return base.Channel.ViewQueueAsync();
        }
    }
}
